### ISSUE TITLE
boto3 error when running createInstance.py

### ISSUE THREAD

**Issue by anthonyrotiroti** [trevor-laher/OnDemandMinecraft#14]
When I run createInstance.py, I'm running into this error in the request: 
```  File "utilityScripts/createInstance.py", line 23, in <module>
    SecurityGroupIds = Config.groupId)
  File "/home/anthony/.local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/anthony/.local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/anthony/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anthony/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value () for parameter groupId is invalid. The value cannot be empty 
```

my config is setup like this: 

``` class Config:
    #AWS Information
    ACCESS_KEY = '***************'
    SECRET_KEY = '***************'
    INSTANCE_ID = ''
    ec2_region = "us-east-1"
    ec2_amis = ['ami-0cfee17793b08a293']
    ec2_keypair = 'arotiroti'
    ec2_secgroups = ['minecraft']
    ec2_instancetype = 't3.micro'

    #SSH Key Path
    SSH_KEY_FILE_PATH = './arotiroti.pem'

    #Server Memory Size
    #This is default to no memory specification but can be: '-Xmx1024M -Xms1024M ' (KEEP TRAILING SPACE)
    MEMORY_ALLOCATION=''
```

I tried passing a security group ID through the SecurityGroupIds argument in the client.createInstances call, but got the same error.

**Comment by trevor-laher** [comment]
SecurityGroupIds = Config.groupId
This seems to be the issue with your code, I don't know where this variable exists. I believe you should be using ec2_secgroups.

**Comment by tranhl** [comment]
@anthonyrotiroti FYI this error occurs because you most likely configured your security group on the wrong region. Change regions on the top right of the AWS console to your preferred region and then try again.

**Comment by trevor-laher** [comment]
I’m also working on a script which will automate all of the website AWS
configuration. Hopefully future users won’t have to run into the same issue.

**Comment by anthonyrotiroti** [comment]
@trevor-laher that Config.groupId line was just from the parameter I added while trying a fix, sorry about that. The output after running the script as it was cloned is the same:
 
`Traceback (most recent call last):
  File "utilityScripts/createInstance.py", line 19, in <module>
    SecurityGroups = Config.ec2_secgroups)
  File "/home/anthony/.local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/anthony/.local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/anthony/.local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anthony/.local/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value () for parameter groupId is invalid. The value cannot be empty`

**Comment by anthonyrotiroti** [comment]
@tranhl I have my region set to US East - N. Virginia, and I'm in Massachusetts. Are there additional steps I should take for the security group?

**Comment by tranhl** [comment]
@anthonyrotiroti Make sure that the AMI you picked was configured for `us-east-1` as well. See the README to pick an AMI for that region.
