### ISSUE TITLE
/static/js/serverStart.js missing

### ISSUE THREAD

**Issue by robschn** [trevor-laher/OnDemandMinecraft#15]
Hello,

Just got everything setup and it works well! One thing I notice is the server didn't start up once the instance was up. I found that serverStart.js is missing from your repo.

Is that correct or am I missing something?

**Comment by trevor-laher** [comment]
Whoops, I’ll remove serverStart.js references. That was just an API call to
the python server to actually boot the instance and Minecraft server
commands. It works without that script, as it is instead called through an
embedded function in the HTML template. I believe the server not starting
will have something to do with the SSH process, your screen configuration,
or you might just need to wait a few minutes before the instance can be
SSH’d into. If it’s not working, just manually perform the commands in
initServerCommands.py by SSHing into the instance, then see which command
is breaking it.

**Comment by robschn** [comment]
Alright thanks! I'll try that out. I appreciate you getting back to me
