### ISSUE TITLE
upgraded server.jar - server wont launch on boot

### ISSUE THREAD

**Issue by osheadavid7** [trevor-laher/OnDemandMinecraft#19]
Hello, 

I just upgraded the minecraft server.jar to 1.15.1 and on reboot/clean-boot server.jar is not running. I think it could be a permissions issue - can you confirm the correct permissions for server.jar?

I used wget as ubuntu to download server.jar and mv to overwrite the existing server.jar. Ownership was then ubuntu:ubuntu. Rebooted to no avail. Chown to root:root like other files in~/., rebooted to no avail, chmod +x to server.jar  (prob not necessary), reboot to no avail.

From the server.py I can the heroku app is sshing in and starting server.ar with sudo java -jar server.jar nogui (with mem args). Calling 'sudo java -jar server.jar nogui' from the cmd line the server starts correctly and I can then connect from minecraft on my laptop. I see that in server.py if prints error info on in the heroku logs I can see COMMAND EXECUTED. Minecraft was launching previous to this as I logged out of the old from the older server.jar immediately before trying to upgrade.

**Comment by payton** [comment]
Have you tried running the entire command (with screen)? I've had permissions issues with screen when messing around with new/multiple users.

**Comment by osheadavid7** [comment]
Running the full screen command "screen -dmS minecraft bash -c 'sudo java -Xmx5120M -Xms2048M  -jar server.jar nogui'" executes without any issue.

**Comment by alexmercerind** [comment]
same issue 😕.
did you fix it?

**Comment by osheadavid7** [comment]
I've given up on using this. No longer running a server.
