### ISSUE TITLE
autoshutdown.sh bad interpreter

### ISSUE THREAD

**Issue by DylanDelobel** [trevor-laher/OnDemandMinecraft#9]
File transfered by filezilla from Windows

`bash: ./autoshutdown.sh: /bin/sh^M: bad interpreter: No such file or directory`

From [StackOverflow](https://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory) 

I've run `sed -i -e 's/\r$//' autoshutdown.sh` and that worked

**Comment by trevor-laher** [comment]
It appears that this might occur when you open the file on a windows machine and some of the line encoding change. The command above does indeed fix this. Just be careful not to open the files on Windows before moving it to the linux instance!
